---
- name: Install and configure Nginx web server
  hosts: all  # This will be overridden by the AAP inventory
  become: true # Use privilege escalation (sudo) to run the tasks

  tasks:
    - name: Ensure sudo and Python are installed (RHEL)
      ansible.builtin.raw: sudo dnf -y install sudo python3
      args:
        creates: /usr/bin/python3
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is installed (RHEL)
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled (RHEL)
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
